// Generated by build_site.py - do not edit by hand.
window.RVW = {
  api: null,          // read-only: the client makes no write requests
  data: "data",
  images: "https://armenian-catalogs.s3.eu-west-par.io.cloud.ovh.net/inscriptions",
  propose: "calfa-co/armenian-inscriptions-data",
  live: "https://raw.githubusercontent.com/calfa-co/armenian-inscriptions-data/main/corrections.json",
  readOnly: true,
};
