// Generated by build_site.py - do not edit by hand.
window.RVW = {
  api: null,          // read-only: the client makes no write requests
  data: "data",
  images: "https://IMAGES-HOST/inscriptions",
  propose: "calfa-co/armenian-inscriptions-data",
  readOnly: true,
};
